# src/constants.py

# FrameMaker Constants
GOLDEN_RATIO = 1.618
SILVER_RATIO = 1.414
SQRT3_RATIO = 1.732
MIN_FRAME_RATIO = 1.0
MAX_FRAME_RATIO = SQRT3_RATIO
SIDE_MARGIN_RATIO = 0.309
DEFAULT_RADIUS = 40

# Colorpick Constants
KMEANS_CLUSTERS = 5
SATURATION_THRESHOLD = 0.5
BRIGHTNESS_THRESHOLD = 0.5
